services:
  - type: web
    name: as-shreads-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: website-name-nithya
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: BUSINESS_NAME
        value: AS Shreads
      - key: BUSINESS_EMAIL
        value: contact@asshreads.com
      - key: BUSINESS_PHONE
        value: +91-9876543210
      - key: BUSINESS_WHATSAPP
        value: +91-9876543210