services:
  - type: web
    name: as-shreads-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: as-shreads-db
          property: connectionString
    healthCheckPath: /api/health

databases:
  - name: as-shreads-db
    databaseName: as_shreads
    user: as_shreads_user