services:
  - type: web
    name: as-shreads-backend
    env: node
    plan: free
    buildCommand: npm install && npm install --only=dev && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: as-shreads-db
          property: connectionString
    autoDeploy: true

databases:
  - name: as-shreads-db
    databaseName: as_shreads
    user: as_shreads_user
    plan: free